import localFont from "next/font/local";
// import "../styles/globals.css"; // Import global CSS file
import "froala-editor/css/froala_editor.pkgd.min.css"; // Froala Editor CSS
import "froala-editor/css/froala_style.min.css"; // Froala Editor style CSS



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
